import Head from 'next/head'
import React, { useRef, useState } from 'react';
import Axios from "axios";
function Contact(){
const [first_name, setFname] = useState();
const [last_name, setLname] = useState();
const [email, setEmail] = useState();
const [company, setCompany] = useState();
const [phone, setPhone] = useState();
const [message, setMessage] = useState();
const [success, setSuccess] = useState();
const [sending, setSending] = useState("SEND MESSAGE");


// const sendMessage = async (event) => {
//   const response = await fetch("/api/contact", {
//     method: "POST",
//     body: JSON.stringify({ first_name: first_name, last_name: last_name, email: email, company: company, phone: phone, message: message }),
//   }).then(res => {
//     console.log(res)
//   });
// };
const handleSubmit = () => {
  setSending("Sending...")
  Axios.post('https://server.suntechlab.com/users/contact', {
    first_name: first_name, last_name: last_name, email: email, company: company, phone: phone, message: message
  }).then(res => {
      console.log(res);
      setSuccess("Thank you for contact us!")
      setSending("SEND MESSAGE")
      setFname(""),setLname(""),setEmail(""),setCompany(""),setPhone(""),setMessage("")
      setTimeout(() => {
        setSuccess("Process completed")
     }, 5000);
  }).catch(err => console.log(err)) } 
  
  return(
    <>
    <Head>
      <title>contact</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/suntechlab-icon.png" />
    </Head>
    <section className="contact_section">
        <div className="contact_banner">
          <h1>Contact Us</h1>
        </div>
        <div className="container">
          <div className="row">
            <div className="col-lg-6">
              <h2 style={{color: '#444', marginBottom: '20px'}}>Leave A Message</h2>
              {success}
              <div className="mb-3 d-flex">
                  <div style={{width: 'calc(50% - 7.5px)', marginRight: '7.5px'}}>
                    <input className="form-control" type="text" name="first_name" value={first_name} onChange={e => setFname(e.target.value)} placeholder="First name*" />
                  </div>
                  <div style={{width: 'calc(50% - 7.5px)', marginLeft: '7.5px'}}>
                    <input className="form-control" type="text" name="last_name" value={last_name} onChange={e => setLname(e.target.value)} placeholder="Last name*" />
                  </div>
                </div>
                <div className="mb-3">
                  <input className="form-control" type="email" name="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Email*" />
                </div>
                <div className="mb-3 d-flex">
                  <div style={{width: 'calc(50% - 7.5px)', marginRight: '7.5px'}}>
                    <input className="form-control" type="text" name="company" value={company} onChange={e => setCompany(e.target.value)} placeholder="Company name" />
                  </div>
                  <div style={{width: 'calc(50% - 7.5px)', marginLeft: '7.5px'}}>
                    <input className="form-control" type="text" name="phone" value={phone} onChange={e => setPhone(e.target.value)} placeholder="Phone*" />
                  </div>
                </div>
                <div className="mb-3">
                  <textarea className="form-control" name="message" value={message} onChange={e => setMessage(e.target.value)} cols={30} rows={3} placeholder={"Message*"} />
                </div>
                <button style={{borderRadius: '5px', background: 'crimson', color: '#fff', padding: '10px 20px', fontWeight: 600, border: 0}} type="submit" onClick={handleSubmit}>{sending}</button>
              </div>
            <div className="col-lg-6">
            </div>
          </div>
        </div>
      </section>
      </>
  )
}

export default Contact;
