import Head from 'next/head'
import Image from 'next/image'
function About(){
  
  return(
    <>
    <Head>
      <title>about</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/suntechlab-icon.png" />
    </Head>
    <section className="about_us">
        <div className="contact_banner">
          <h1>About Us</h1>
        </div>
        <div className="container">
          <div style={{ padding: '40px 0px' }} className="row">
            <div className="col-lg-6 d-flex align-items-center">
              <div className="item">
                <div className="">
                  <h2>About Us
                    <a href="#">Grow Your Business With us!!</a></h2>
                  <p>
                    Suntechlab is an established Website Design and Development Company. We started our journey in 2018 and working in line with modern trends. And we are moving forward by working successfully according to the needs of the present time. We have set our goal to become the most dependable, trendy, favored web design and development agency in the industry by implementing high-quality services to our clients at a competitive price.
                  </p>
                </div>
              </div>
            </div>
            <div className="col-lg-6 d-flex align-items-center">
              <div className="d-flex align-items-center justify-content-center unset-img">
                <Image className="custom-img" src="/images/about.png" layout="fill" alt="Suntechlab" />
              </div>
            </div>
          </div>
        </div>
      </section>
      </>
  )
}

export default About;
