import Head from 'next/head'
import React, { useEffect, useState } from "react";
import { EditorState, convertToRaw } from "draft-js";
import "react-draft-wysiwyg/dist/react-draft-wysiwyg.css";
import draftToHtml from 'draftjs-to-html';
import dynamic from "next/dynamic";

const Editor = dynamic(
  () => {
    return import("react-draft-wysiwyg").then(mod => mod.Editor);
  },
  { ssr: false }
);

function About(){
    const [editorState, setEditorState] = useState(() =>
    EditorState.createEmpty()
  );
  useEffect(() => {
    console.log(draftToHtml(convertToRaw(editorState.getCurrentContent())));
  }, [editorState]);
  function uploadImageCallBack(file) {
    return new Promise(
      (resolve, reject) => {
        const xhr = new XMLHttpRequest();
        xhr.open('POST', 'https://api.imgur.com/3/image');
        xhr.setRequestHeader('Authorization', 'Client-ID 513857b07bc8dc4');
        const data = new FormData();
        data.append('image', file);
        xhr.send(data);
        xhr.addEventListener('load', () => {
          const response = JSON.parse(xhr.responseText);
          resolve(response);
        });
        xhr.addEventListener('error', () => {
          const error = JSON.parse(xhr.responseText);
          reject(error);
        });
      }
    );
  }
    // function uploadImageCallBack(file) {
    // return new Promise(
      // (resolve, reject) => {
        // resolve({ data: { link: "https://api.imgur.com/3/image" } });
      // }
    // );
  // }
  return(
    <>
    <Head>
      <title>about</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/suntechlab-icon.png" />
    </Head>
    <div style={{paddingTop:"62px"}}>
      <h1>React Editors</h1>
      <h2>Start editing to see some magic happen!</h2>
      <div style={{ border: "1px solid black", padding: '2px', minHeight: '400px' }}>
        <Editor
          editorState={editorState}
          onEditorStateChange={setEditorState}
          placeholder="The message goes here..."
          toolbar={{
            inline: { inDropdown: true },
            list: { inDropdown: true },
            textAlign: { inDropdown: true },
            link: { inDropdown: true },
            history: { inDropdown: true },
            image: { uploadCallback: uploadImageCallBack, alt: { present: true, mandatory: false } },
            }}
        />
        <textarea disabled rows="3" cols="10" value={draftToHtml(convertToRaw(editorState.getCurrentContent()))}></textarea>
        {/* <textarea disabled rows="10" cols="30" value={JSON.stringify(editorState, null, 4)}></textarea> */}
      </div>
    </div>
      </>
  )
}

export default About;
