import Head from 'next/head'
import React, { useRef, useState } from 'react';
import Axios from "axios";
import Image from 'next/image'
function CreatePost(){
    const [title, setTitle] = useState();
    const [price, setPrice] = useState();
    const [procategory, setCategory] = useState();
    const [subcategory, setSubCategory] = useState();
    const [description, setDescription] = useState();
    const [image, setImage] = useState([]);
    const [createObjectURL, setCreateObjectURL] = useState([]);
    const el = useRef();
    const [success, setSuccess] = useState();
    const [sending, setSending] = useState("SEND MESSAGE");

// const sendMessage = async (event) => {
//   const response = await fetch("/api/contact", {
//     method: "POST",
//     body: JSON.stringify({ first_name: first_name, last_name: last_name, email: email, company: company, phone: phone, message: message }),
//   }).then(res => {
//     console.log(res)
//   });
// };
const uploadToClient = (event) => {
    let images =[];
    const i = event.target.files;
    console.log(i);
    setImage(i);
    for(var img=0;img<i.length; img++){
      images.push(URL.createObjectURL(i[img]));
    }
    setCreateObjectURL(images);
    
};

const handleSubmit = (event) => {
    event.preventDefault()
    const formData = new FormData();
    formData.append('title', title);
    formData.append('price', price);
    formData.append('procategory', procategory);
    formData.append('subcategory', subcategory);
    formData.append('description', description);
    for(var a = 0; a<image.length; a++){      
        formData.append('image', image[a]); // appending file
      }
  setSending("Sending...")
  Axios.post('https://server.suntechlab.com/posts/add',formData, {
    
  }).then(res => {
      console.log(res);
      setSuccess("Thank you for contact us!")
      setSending("SEND MESSAGE")
  }).catch(err => console.log(err)) } 
  
  return(
    <>
    <Head>
      <title>contact</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/suntechlab-icon.png" />
    </Head>
    <section className="contact_section">
        <div className="contact_banner">
          <h1>Contact Us</h1>
        </div>
        <div className="container">
          <div className="row">
            <div className="col-lg-6">
              <h2 style={{color: '#444', marginBottom: '20px'}}>Leave A Message</h2>
              {success}
              <div className="mb-3 d-flex">
                  <div style={{width: 'calc(50% - 7.5px)', marginRight: '7.5px'}}>
                    <input className="form-control" type="text" name="title" onChange={e => setTitle(e.target.value)} placeholder="Product titel" />
                  </div>
                  <div style={{width: 'calc(50% - 7.5px)', marginLeft: '7.5px'}}>
                    <input className="form-control" type="text" name="price" onChange={e => setPrice(e.target.value)} placeholder="Price" />
                  </div>
                </div>
                <div className="mb-3">
                  <input className="form-control" type="text" name="procategory" onChange={e => setCategory(e.target.value)} placeholder="Category*" />
                </div>
                <div className="mb-3">
                  <div>
                    <input className="form-control" type="text" name="subcategory" onChange={e => setSubCategory(e.target.value)} placeholder="Sub category" />
                  </div>
                </div>
                <div className="mb-3">
                  <textarea className="form-control" name="description" onChange={e => setDescription(e.target.value)} cols={30} rows={3} placeholder={"Message*"} />
                </div>
                <div className="mb-3">
            <div className="row">
            {createObjectURL.map((img, index)=>{
              return(                
                  <div className="col-lg-2 col-md-2 col-sm-2 col-3" key={index}>
                    <div className="upload-image">
                      <Image src={img} width={6} height={4} alt={img} />
                    </div>
                  </div>   
              )
            })}
            </div>
            <h4>Select Image</h4>
            <input type="file" name="image" ref={el} onChange={uploadToClient} multiple />
            </div>
                <button style={{borderRadius: '5px', background: 'crimson', color: '#fff', padding: '10px 20px', fontWeight: 600, border: 0}} type="submit" onClick={handleSubmit}>{sending}</button>
              </div>
            <div className="col-lg-6">
            </div>
          </div>
        </div>
      </section>
      </>
  )
}

export default CreatePost;
